-- StackMap PostgreSQL Schema                                                                                                                                                                                         
CREATE TABLE servers (                                                                                                                                                                                                
    id VARCHAR(50) PRIMARY KEY,                                                                                                                                                                                       
    zerotier_ip VARCHAR(45),                                                                                                                                                                                          
    os_version VARCHAR(100),                                                                                                                                                                                          
    status VARCHAR(20) DEFAULT 'online'                                                                                                                                                                               
);                                                                                                                                                                                                                    
                                                                                                                                                                                                                      
CREATE TABLE subflows (                                                                                                                                                                                               
    id VARCHAR(100) PRIMARY KEY,                                                                                                                                                                                      
    label VARCHAR(255) NOT NULL,                                                                                                                                                                                      
    server_id VARCHAR(50) REFERENCES servers(id),                                                                                                                                                                     
    visibility VARCHAR(20) CHECK (visibility IN ('public', 'private'))                                                                                                                                                
);                                                                                                                                                                                                                    
                                                                                                                                                                                                                      
CREATE TABLE nodes (                                                                                                                                                                                                  
    id VARCHAR(64) PRIMARY KEY,                                                                                                                                                                                       
    label VARCHAR(255) NOT NULL,                                                                                                                                                                                      
    image VARCHAR(512),                                                                                                                                                                                               
    status VARCHAR(20) DEFAULT 'online',                                                                                                                                                                              
    container_network_ip VARCHAR(45),                                                                                                                                                                                 
    coolify_service_hash VARCHAR(255),                                                                                                                                                                                
    compose_project_name VARCHAR(255),                                                                                                                                                                                
    proxy_domain_rule TEXT,                                                                                                                                                                                           
    in_vplan BOOLEAN NOT NULL DEFAULT TRUE,                                                                                                                                                                           
    subflow_id VARCHAR(100) REFERENCES subflows(id)                                                                                                                                                                   
);                                                                                                                                                                                                                    
                                                                                                                                                                                                                      
CREATE TABLE edges (                                                                                                                                                                                                  
    id VARCHAR(128) PRIMARY KEY,                                                                                                                                                                                      
    source_node VARCHAR(64) REFERENCES nodes(id),                                                                                                                                                                     
    target_node VARCHAR(64) REFERENCES nodes(id),                                                                                                                                                                     
    edge_type VARCHAR(50),                                                                                                                                                                                            
    discovered_via VARCHAR(50),                                                                                                                                                                                       
    shared_resource_name VARCHAR(255)                                                                                                                                                                                 
);                                                                                                                                                                                                                    
                                                                                                                                                                                                                      
-- Indexing for performance                                                                                                                                                                                           
CREATE INDEX idx_nodes_subflow ON nodes(subflow_id);                                                                                                                                                                  
CREATE INDEX idx_edges_source ON edges(source_node);                                                                                                                                                                  
CREATE INDEX idx_edges_target ON edges(target_node);
